---

- name: Fail if ATMOUSERNAME or USERSSHKEYS is undefined
  fail:
    msg: "ATMOUSERNAME or USERSSHKEYS is undefined but required for this role."
  when: ATMOUSERNAME is not defined or USERSSHKEYS is not defined

- name: 'local user account created'
  user:
    name: '{{ ATMOUSERNAME }}'
    state: 'present'
    shell: '/bin/bash'

- name: 'home directory created for user'
  file:
    path: '/home/{{ ATMOUSERNAME }}'
    state: 'directory'
    mode: 0700

- name: 'Add users ssh keys to authorized_keys'
  authorized_key:
    user: root
    state: present
    key: "{{ item }}"
  with_items: '{{ USERSSHKEYS }}'
  become: yes
  when: USERSSHKEYS is defined

- name: 'verify that home directory of user exists (to avoid ansible error)'
  stat:
    path: "/home/{{ ATMOUSERNAME }}"
  register: user_home_dir
  when: ATMOUSERNAME is defined

- name: 'Add users ssh keys to authorized_keys to home directory of user'
  authorized_key:
    user: "{{ ATMOUSERNAME }}"
    state: present
    exclusive: no
    key: '{{ item }}'
  with_items: '{{ USERSSHKEYS }}'
  when: ATMOUSERNAME is defined and USERSSHKEYS is defined and user_home_dir.stat.exists

- name: 'Restart SSH Ubuntu'
  service:
    name: "ssh"
    state: restarted
  when: ansible_distribution == "Ubuntu"

- name: 'Restart SSH CentOS'
  service:
    name: "sshd"
    state: restarted
  when: ansible_distribution == "CentOS"
